name: Prettier check

on: [push, pull_request]

jobs:
  test:
    name: "Prettier checkup"

    runs-on: ubuntu-latest

    steps:
	  - name: "checkout code"
	    uses: actions/checkout@v2
	  - run: "npm install"
	  - run: "npm test"
